version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo ===== pre build phase =====

      - export DOCKER_CONTENT_TRUST=1

      - export ECR_REPOS_DOMAIN=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - export ECR_REPOS_URI=${ECR_REPOS_DOMAIN}/${APP_NAME}
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo ECR_REPOS_URI=${ECR_REPOS_URI}

  build:
    commands:
      - echo ===== build phase =====
      - echo Docker Build started on `date`
      - echo Building the Docker image...
      - docker buildx build -f Dockerfile.pnpm -t ${APP_NAME}:latest .
      - docker tag ${APP_NAME}:latest ${ECR_REPOS_URI}:${IMAGE_TAG}
      - docker image ls
      - echo Completed the ${APP_NAME} Docker image build.

      - export DOCKER_CONTENT_TRUST=0

  post_build:
    commands:
      - echo ===== post build phase =====
      - echo Logging in to Amazon ECR.
      - aws ecr get-login-password | docker login --username AWS --password-stdin "https://${ECR_REPOS_DOMAIN}"
      - echo Docker Image ${APP_NAME} pushing to ECR on `date`
      - docker push ${ECR_REPOS_URI}:${IMAGE_TAG}
      - echo '[{"name":"app","imageUri":"'$ECR_REPOS_URI':'$IMAGE_TAG'"}]'  > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
